import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const assets=path.join(repo,"app/src/main/assets");
const failures=[];
const fail=(scope,error)=>failures.push(`${scope}: ${error?.stack||error}`);
class Param{constructor(v=0){this.value=v}setTargetAtTime(v){this.value=v}setValueAtTime(v){this.value=v}linearRampToValueAtTime(v){this.value=v}exponentialRampToValueAtTime(v){this.value=v}cancelScheduledValues(){}cancelAndHoldAtTime(){}}
class AudioNode{constructor(){for(const k of ["gain","frequency","detune","delayTime","Q","playbackRate","pan","threshold","knee","ratio","attack","release","offset"])this[k]=new Param(k==="gain"||k==="playbackRate"?1:0);this.fftSize=1024;this.smoothingTimeConstant=0;this.type="sine";this.loop=false;this.buffer=null;this.curve=null;this.onended=null}connect(n){return n}disconnect(){}start(){}stop(){this.onended?.()}setPeriodicWave(){}getFloatTimeDomainData(a){a.fill(0)}}
class AudioBuffer{constructor(channels,length,sampleRate){this.numberOfChannels=channels;this.length=length;this.sampleRate=sampleRate;this.duration=length/sampleRate;this.data=Array.from({length:channels},()=>new Float32Array(length))}getChannelData(i){return this.data[i]}copyToChannel(data,i){this.data[i].set(data.subarray?data.subarray(0,this.length):data)}}
class AudioContext{constructor(){this.currentTime=0;this.sampleRate=48000;this.state="running";this.destination=new AudioNode()}createGain(){return new AudioNode()}createOscillator(){return new AudioNode()}createBiquadFilter(){return new AudioNode()}createDelay(){return new AudioNode()}createDynamicsCompressor(){return new AudioNode()}createAnalyser(){return new AudioNode()}createBuffer(c,l,r){return new AudioBuffer(c,l,r)}createBufferSource(){return new AudioNode()}createChannelMerger(){return new AudioNode()}createChannelSplitter(){return new AudioNode()}createWaveShaper(){return new AudioNode()}createStereoPanner(){return new AudioNode()}createConvolver(){return new AudioNode()}createConstantSource(){return new AudioNode()}createScriptProcessor(){const n=new AudioNode();n.onaudioprocess=null;return n}createPeriodicWave(){return {}}resume(){this.state="running";return Promise.resolve()}close(){return Promise.resolve()}}
class ClassList{constructor(){this.s=new Set()}add(...x){x.forEach(v=>this.s.add(v))}remove(...x){x.forEach(v=>this.s.delete(v))}toggle(v,on){if(on===undefined)on=!this.s.has(v);on?this.s.add(v):this.s.delete(v);return on}contains(v){return this.s.has(v)}}
class Style{setProperty(k,v){this[k]=v}}
class Element{constructor(tag="div"){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style=new Style();this.classList=new ClassList();this.className="";this.attributes={};this.textContent="";this._innerHTML="";this.value="";this.width=640;this.height=160;this.parentElement=null}append(...xs){xs.forEach(x=>this.appendChild(x))}appendChild(x){if(x){x.parentElement=this;this.children.push(x)}return x}prepend(x){if(x){x.parentElement=this;this.children.unshift(x)}return x}replaceChildren(...xs){this.children=[];this.append(...xs)}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this)}set innerHTML(v){this._innerHTML=String(v);if(v==="")this.children=[]}get innerHTML(){return this._innerHTML}setAttribute(k,v){this.attributes[k]=String(v)}getAttribute(k){return this.attributes[k]}addEventListener(){}removeEventListener(){}setPointerCapture(){}releasePointerCapture(){}querySelector(){return null}querySelectorAll(){return []}closest(){return null}getBoundingClientRect(){return {left:0,top:0,width:160,height:80}}getContext(){return {fillStyle:"",strokeStyle:"",lineWidth:1,globalAlpha:1,shadowColor:"",shadowBlur:0,save(){},restore(){},clearRect(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}}}}
class Image{constructor(){this.naturalWidth=0;this.naturalHeight=0;this.decoding="";this.onload=null;this.onerror=null;this._src=""}set src(v){this._src=String(v||"")}get src(){return this._src}}
const ids=new Map();
const document={head:new Element("head"),body:new Element("body"),documentElement:new Element("html"),hidden:false,styleSheets:[],createElement:t=>new Element(t),createElementNS:(_ns,t)=>new Element(t),getElementById:id=>ids.get(id)||null,querySelector:()=>null,querySelectorAll:()=>[],write(){}};
const listeners=new Map();
const context={console,Math,JSON,Date,Number,String,Boolean,Array,Object,Map,Set,WeakMap,Promise,Float32Array,Uint8Array,Int32Array,URLSearchParams,AudioContext,webkitAudioContext:AudioContext,Image,document,navigator:{vibrate(){}},location:{search:""},performance:{now:()=>0},devicePixelRatio:1,queueMicrotask,requestAnimationFrame:fn=>setTimeout(()=>fn(0),0),cancelAnimationFrame:clearTimeout,setTimeout,clearTimeout,setInterval,clearInterval,CustomEvent:class{constructor(type,o={}){this.type=type;this.detail=o.detail}},addEventListener(type,fn){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn)},removeEventListener(type,fn){listeners.get(type)?.delete(fn)},dispatchEvent(e){listeners.get(e.type)?.forEach(fn=>fn(e));return true},getComputedStyle:()=>({getPropertyValue:()=>"#9fe7ff"}),localStorage:{getItem(){return null},setItem(){},removeItem(){}},indexedDB:{open(){throw new Error("IndexedDB should not be touched during construction smoke")}}};
context.window=context;context.globalThis=context;context.parent=context;
vm.createContext(context);
function load(rel){const p=path.join(assets,rel);if(!fs.existsSync(p))throw new Error(`missing ${rel}`);vm.runInContext(fs.readFileSync(p,"utf8"),context,{filename:rel})}
const controlDefs=fs.readdirSync(path.join(assets,"controls")).filter(x=>x.endsWith(".js")&&x!=="spec-core.js").sort().map(x=>"controls/"+x);
const core=["module-ids.js","module-capabilities.js","module-boilerplate.js","state-keys.js","event-registry.js","control-descriptors.js","control-surface-library.js",...controlDefs,"controls/spec-core.js","control-surface-renderer.js","state-schema.js","module-manifest.js","module-contract.js","patch-transport.js","clock-standard.js","native-mic.js","native-live-wire.js","clean-mic.js","pcm-library.js","grain-library.js","dsp-source-family.js"];
for(const f of core)try{load(f)}catch(e){fail(`load ${f}`,e)}
const MS=context.MultiSynth||{};
const catalog=Object.values(MS.ModuleIds?.CATALOG||{});
try{load("modules/carrier-engine.js")}catch(e){fail("load modules/carrier-engine.js",e)}
for(const rel of [...new Set(catalog.map(x=>x.moduleScript))])try{load(rel)}catch(e){fail(`load ${rel}`,e)}
for(const f of ["module-standards-audit.js","node-graph-engine.js","patch-bpm-sync.js","node-audio-graph.js","clock-bus.js"])try{load(f)}catch(e){fail(`load ${f}`,e)}
try{if(!MS.ModuleStandards?.report?.ok)throw new Error(JSON.stringify(MS.ModuleStandards?.report?.errors||["standards audit unavailable"]));console.log(`standards: ${MS.ModuleStandards.report.checked} modules`)}catch(e){fail("module standards",e)}
const E=MS.NodeGraphEngine,C=MS.ModuleContract,A=MS.NodeAudioGraph,M=MS.ModuleManifest,T=MS.PatchTransport;
const ctx=new AudioContext(),native={mic:{},liveWire:{},midi:{},audio:{}},moduleIds=[];
for(const meta of M?.all||[]){try{const id=E.addModule(meta.id);moduleIds.push(id);const rt=E.createModuleRuntime(id,{audioContext:ctx,native,node:{hasUpstream:false}});C.update(id,{});const saved=C.serialize(id);C.restore(id,saved);if(meta.capabilities.includes("noteInput")){C.noteOn(id,60,100);C.noteOff(id,60);C.panic(id)}if(meta.capabilities.includes("audioInput")&&!rt.input)throw new Error("audioInput module did not create input");if(meta.capabilities.includes("audioOutput")&&!rt.output)throw new Error("audioOutput module did not create output")}catch(e){fail(`module ${meta.id}`,e)}}
console.log(`runtime: ${moduleIds.length}/${M?.all?.length||0} modules constructed`);
try{const id=moduleIds.find(id=>E.getModule(id)?.type===MS.ModuleIds.PURE_SYNTH);if(!id)throw new Error("PureSynth runtime missing");const rt=C.getRuntime(id);if(!rt.user?.pureSource)throw new Error("PureSynth did not start continuous source");const before=Number(rt.state.frequencyHz);C.update(id,{frequencyHz:523.25});if(Math.abs(rt.state.frequencyHz-523.25)>.0001||rt.state.frequencyHz===before)throw new Error("Pitch control did not change frequencyHz");C.midi(id,{status:0x90,data1:60,data2:100});const c4=440*Math.pow(2,(60-69)/12);if(Math.abs(rt.state.frequencyHz-c4)>.0001)throw new Error("Keyboard C4 did not set its frequency");C.midi(id,{status:0x80,data1:60,data2:0});if(Math.abs(rt.state.frequencyHz-c4)>.0001)throw new Error("Key release changed continuous frequency");C.midi(id,{status:0x90,data1:69,data2:100});if(Math.abs(rt.state.frequencyHz-440)>.0001)throw new Error("Keyboard A4 did not set 440 Hz");C.midi(id,{status:0xb0,data1:64,data2:127});if(Object.prototype.hasOwnProperty.call(rt.state,"sustainPedal"))throw new Error("Sustain control changed PureSynth state");C.midi(id,{status:0xb0,data1:1,data2:64});if(Math.abs(rt.state.modulation-64/127)>.0001)throw new Error("Mod control did not change modulation");C.midi(id,{status:0xb0,data1:7,data2:32});if(Math.abs(rt.state.level-32/127)>.0001)throw new Error("Level control did not change level");C.midi(id,{status:0xb0,data1:11,data2:96});if(Math.abs(rt.state.expression-96/127)>.0001)throw new Error("Expression control did not change expression");C.midi(id,{status:0xe0,data1:127,data2:127});if(rt.state.pitchBend<1.9||rt.state.pitchBend>2.01)throw new Error("Pitch bend did not change pitchBend state");C.midi(id,{status:0xc0,data1:2});if(rt.state.program!==2||rt.state.waveform!=="triangle")throw new Error("Program control did not change waveform");C.panic(id);if(!rt.user?.pureSource)throw new Error("Panic stopped continuous PureSynth source");console.log("puresynth reference source: controls changed the expected state and continuous source stayed alive")}catch(e){fail("puresynth reference source contract",e)}
try{const synthTypes=[MS.ModuleIds.QUAD_SYNTH,MS.ModuleIds.NO_QUARTER];for(const type of synthTypes){const id=moduleIds.find(id=>E.getModule(id)?.type===type);if(!id)throw new Error(`${type} runtime missing`);const def=C.getDefinition(type),rt=C.getRuntime(id);if(def.version!=="performance-midi-1")throw new Error(`${type} unexpected runtime version ${def.version}`);if(typeof def.midiMessage!=="function")throw new Error(`${type} has no real MIDI message handler`);C.midi(id,{status:0x90,data1:62,data2:101});if(!rt.user?.voices?.has("62"))throw new Error(`${type} Note On did not create voice`);C.midi(id,{status:0xb0,data1:64,data2:127});C.midi(id,{status:0x80,data1:62,data2:0});if(!rt.user.voices.has("62")||!rt.user.sustained?.has("62"))throw new Error(`${type} CC64 sustain did not hold note`);C.midi(id,{status:0xb0,data1:64,data2:0});if(rt.user.voices.has("62")||rt.user.sustained?.has("62"))throw new Error(`${type} CC64 release did not clear note`);C.midi(id,{status:0x90,data1:63,data2:100});C.update(id,{sustainPedal:true});C.midi(id,{status:0x80,data1:63,data2:0});if(!rt.user.voices.has("63")||!rt.user.sustained?.has("63"))throw new Error(`${type} UI sustain did not hold note`);C.update(id,{sustainPedal:false});if(rt.user.voices.has("63")||rt.user.sustained?.has("63"))throw new Error(`${type} UI sustain off did not release note`);C.midi(id,{status:0x90,data1:64,data2:110});const voice=rt.user.voices.get("64"),source=voice?.sources?.find(o=>Number(o?.frequency?.value)>0),before=Number(source?.frequency?.value);C.midi(id,{status:0xe0,data1:127,data2:127});if(rt.state.pitchBend<1.9||rt.state.pitchBend>2.01)throw new Error(`${type} Pitch Bend state/range failed`);if(source&&!(Number(source.frequency.value)>before))throw new Error(`${type} active voice did not retune on Pitch Bend`);C.midi(id,{status:0xb0,data1:7,data2:48});if(Math.abs(rt.state.level-48/127)>.0001)throw new Error(`${type} CC7 level mapping failed`);C.midi(id,{status:0xb0,data1:11,data2:80});if(Math.abs(rt.state.expression-80/127)>.0001)throw new Error(`${type} CC11 expression mapping failed`);C.midi(id,{status:0xb0,data1:73,data2:64});if(Math.abs(rt.state.attack-(64/127*4))>.0001)throw new Error(`${type} CC73 attack mapping failed`);C.panic(id)}console.log(`performance synth MIDI: ${synthTypes.length} family instruments passed note/sustain/pitch/level/expression/envelope lifecycle`)}catch(e){fail("performance synth MIDI family",e)}
try{const followers=moduleIds.filter(id=>M.get(E.getModule(id).type).capabilities.includes("clockFollower")),father=followers.find(id=>E.getModule(id)?.type===MS.ModuleIds.FATHER_TIME),statefulFollowers=followers.filter(id=>id!==father&&Object.prototype.hasOwnProperty.call(E.getModule(id)?.state||{},"running"));if(!followers.length)throw new Error("no clock followers registered");if(!father)throw new Error("father-time not registered as clock follower");if(Object.prototype.hasOwnProperty.call(E.getModule(father)?.state||{},"running"))throw new Error("father-time must be always-on and have no running state");T.setBpm(120);T.start();for(const id of statefulFollowers)if(E.getModule(id)?.state?.running!==true)throw new Error(`${E.getModule(id)?.type} did not follow MIDI Start`);for(let frame=0;frame<=12288;frame+=128)T.ingestTimebase({frame,sampleRate:48000});T.stop();for(const id of statefulFollowers)if(E.getModule(id)?.state?.running!==false)throw new Error(`${E.getModule(id)?.type} did not follow MIDI Stop`);if(Object.prototype.hasOwnProperty.call(E.getModule(father)?.state||{},"running"))throw new Error("father-time acquired forbidden running state");console.log(`midi transport: ${statefulFollowers.length} stateful followers + Father Time always-on master passed`)}catch(e){fail("midi transport followers",e)}
try{const alchemy=moduleIds.find(id=>E.getModule(id).type===MS.ModuleIds.ALCHEMY_MIXER),source=moduleIds.find(id=>{const m=E.getModule(id);return m.type!==MS.ModuleIds.ALCHEMY_MIXER&&M.get(m.type).capabilities.includes("audioOutput")}),processor=moduleIds.find(id=>{const m=E.getModule(id),c=M.get(m.type).capabilities;return c.includes("audioInput")&&c.includes("audioOutput")&&id!==source&&id!==alchemy});if(!source||!processor||!alchemy)throw new Error("missing graph smoke endpoints");const e1=E.connectNodes(E.moduleOut(source),E.moduleIn(processor)),e2=E.connectNodes(E.moduleOut(processor),E.moduleInput(alchemy,0));E.setModuleState(alchemy,{channels:{0:{level:.75,mute:false,solo:false}}});const saved=E.serialize({smoke:true});E.disconnectNodes(e1);E.disconnectNodes(e2);E.restore(saved);if(E.graph().connections.length<2)throw new Error("graph restore lost connections");if(E.getModule(alchemy)?.state?.channels?.[0]?.level!==.75)throw new Error("Alchemy channel state lost");console.log("node graph: connect/disconnect/serialize/restore passed")}catch(e){fail("node graph",e)}
try{A.start();await Promise.resolve();await Promise.resolve();A.noteOn(60,100);A.noteOff(60);A.panic();A.setMaster(.8);if(!A.context||!A.collector||!A.masterAnalyser)throw new Error("audio graph outputs unavailable");console.log("sound engine: rebuild/note/master passed")}catch(e){fail("sound engine",e)}
try{const surface=MS.ControlSurface,renderer=MS.ControlSurfaceRenderer;if(!surface||!renderer)throw new Error("shared control surface unavailable");let rendered=0;for(const type of surface.listControls()){const host=new Element("section"),value=["knob","dial","turntable","fader","ribbon","xy","meter"].includes(type)?{default:.5,min:0,max:1,step:.01}:null,spec={id:`smoke-${type}`,control:type,label:type.toUpperCase(),...(value?{value}:{})};const result=renderer.mount(host,spec);if(!result||host.children[0]!==result)throw new Error(`${type} failed to mount`);if(result.dataset.control!==type)throw new Error(`${type} renderer lost control identity`);rendered++}console.log(`controls: ${rendered}/${surface.listControls().length} shared primitives rendered`)}catch(e){fail("controls",e)}
try{E.clear()}catch(e){fail("cleanup",e)}
if(failures.length){console.error("\nRUNTIME SMOKE FAILURES");for(const f of failures)console.error("- "+f);process.exit(1)}
console.log("runtime smoke passed");